CREATE TABLE `KATEYTHINSI` (
  `t_id` INT PRIMARY KEY,
  `onoma tomea` VARCHAR(100) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE `STUDENT` (
  `AM` INT PRIMARY KEY,
  `name` VARCHAR(50) NOT NULL,
  `birthdate` DATE NOT NULL,
  `etos eisagogis` INT NOT NULL,
  `email` VARCHAR(50),
  `mothername` VARCHAR(50),
  `fathername` VARCHAR(50),
  `address` VARCHAR(255),
  `status` ENUM('GRAD', 'POST-GRAD'),
  `active student` ENUM('YES', 'NO'),
  `phone` INT,
  `kid` INT,
  FOREIGN KEY (`kid`) REFERENCES `KATEYTHINSI`(`t_id`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE `LESSON` (
  `lesson id` INT PRIMARY KEY,
  `ECTS` INT NOT NULL,
  `title` VARCHAR(100) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE `DIDASKALIA` (
  `kod math` INT,
  `semester` INT,
  `ergastirio` ENUM('YES', 'NO'),
  PRIMARY KEY (`kod math`, `semester`),
  FOREIGN KEY (`kod math`) REFERENCES `LESSON`(`lesson id`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE `EGGRAFI` (
  `AM` INT NOT NULL,
  `id math` INT NOT NULL,
  `semester` INT NOT NULL,
  `grade` FLOAT,
  `date of sub` date,
  PRIMARY KEY (`AM`, `id math`, `semester`),
  FOREIGN KEY (`AM`) REFERENCES `STUDENT`(`AM`) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (`id math`) REFERENCES `DIDASKALIA`(`kod math`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE `PROFESSOR` (
  `AM` INT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(255),
  `email` VARCHAR(100),
  `status` VARCHAR(100),
  `phone` INT(10)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE `DIDASKEI` (
  `AM prof` INT NOT NULL,
  `lesson` INT NOT NULL,
  PRIMARY KEY (`AM prof`, `lesson`),
  FOREIGN KEY (`AM prof`) REFERENCES `PROFESSOR`(`AM`) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (`lesson`) REFERENCES `DIDASKALIA`(`kod math`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE `PISTOPOIHTIKO` (
  `p_id` INT PRIMARY KEY,
  `type` VARCHAR(100) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE `AITEITAI` (
  `AM` INT,
  `p_id` INT,
  `date` DATE,
  `completed` ENUM('YES', 'NO'),
  PRIMARY KEY(`p_id`, `AM`),
  FOREIGN KEY (`AM`) REFERENCES `STUDENT`(`AM`) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (`p_id`) REFERENCES `PISTOPOIHTIKO`(`p_id`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE `DIPLOMATIKI` (
  `dipl id` INT PRIMARY KEY,
  `AM student` INT NOT NULL UNIQUE,
  `epiblepon` INT NOT NULL,
  `title` VARCHAR(50),
  `assignment date` DATE NOT NULL,
  `min completion date` DATE NOT NULL,
  FOREIGN KEY (`epiblepon`) REFERENCES `PROFESSOR`(`AM`) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (`AM student`) REFERENCES `STUDENT`(`AM`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE `KORMOU` (
  `id_mathima` INT PRIMARY KEY,
  `epiloghs` ENUM('YES', 'NO'),
  FOREIGN KEY (`id_mathima`) REFERENCES `LESSON`(`lesson id`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
CREATE TABLE `TOMEA` (
  `id_mathima` INT PRIMARY KEY,
  `omada` INT NOT NULL,
  FOREIGN KEY (`id_mathima`) REFERENCES `LESSON`(`lesson id`) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (`omada`) REFERENCES `KATEYTHINSI`(`t_id`) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8;